# Generated by Django 2.0.5 on 2018-05-10 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_auto_20180507_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='content',
            new_name='comment_content',
        ),
    ]
